services:
  json-to-brep-builder:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: json-to-brep-builder
    restart: unless-stopped
    ports:
      - "5002:5002"
    volumes:
      - .:/app
    working_dir: /app
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE