services:
  brep-manipulator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: brep-manipulator
    restart: unless-stopped
    ports:
      - "5002:5002"
    environment:
      - DISPLAY=:1
      - XAUTHORITY=/root/.Xauthority
      - LIBGL_ALWAYS_SOFTWARE=1
      - MESA_GL_VERSION_OVERRIDE=3.3
      - GALLIUM_DRIVER=llvmpipe
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /root/.Xauthority:/root/.Xauthority:ro
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE